name: Deploy Sample .NET Core to IIS on Azure VM

env:
  DOTNET_VERSION: '6.0.x'
  PROJECT_PATH: 'SampleDotNetApp/SampleDotNetApp.csproj'
  SOLUTION_PATH: 'SampleDotNetApp.sln'
  PUBLISH_FOLDER: 'publish_output'

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  build-publish:
    name: Build and Publish .NET App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore .NET Dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build .NET Application
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Publish .NET Application
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} \
            --configuration Release \
            --output ${{ env.PUBLISH_FOLDER }}

      - name: Upload Published Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app-publish
          path: ${{ env.PUBLISH_FOLDER }}
          retention-days: 1

  deploy-to-iis-vm:
    name: Deploy to IIS on Azure VM
    runs-on: ubuntu-latest
    needs: build-publish

    steps:
      - name: Download Published Artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app-publish
          path: ./downloaded_app

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Test SSH connection
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
          'echo "Hello from GitHub Actions"'

      - name: Copy and Deploy to IIS
        run: |
          echo "Stopping IIS Site (if exists)..."
          sshpass -p "${{ secrets.VM_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
          "powershell.exe -Command \"
            if (Test-Path IIS:\Sites\${{ secrets.IIS_SITE_NAME }}) {
              Stop-WebSite -Name '${{ secrets.IIS_SITE_NAME }}'
              Write-Host 'Site stopped.'
            } else {
              Write-Host 'Site not found. Skipping stop.'
            }
          \""

          echo "Copying files to remote IIS site directory..."
          sshpass -p "${{ secrets.VM_PASSWORD }}" \
          scp -r -o StrictHostKeyChecking=no ./downloaded_app/* \
          ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:'${{ secrets.IIS_SITE_PATH }}'

          echo "Starting IIS Site (if exists)..."
          sshpass -p "${{ secrets.VM_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
          "powershell.exe -Command \"
            if (Test-Path IIS:\Sites\${{ secrets.IIS_SITE_NAME }}) {
              Start-WebSite -Name '${{ secrets.IIS_SITE_NAME }}'
              Write-Host 'Site started.'
            } else {
              Write-Host 'Site not found. Skipping start.'
            }
          \""
